# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -trimpath -tags urfave_cli_no_docs -ldflags="-s -w -linkmode external --extldflags '-static'" -o portScan.exe ./cmd/go-portScan.go
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portScan
        path: portScan.exe
